### PR TITLE
Additional Resources for Spring / Spring Boot Learning

### PR DESCRIPTION
**Pull request by mikhi-mh**
Hi @danvega , thanks for this compiled various resources.
---
 I have also compiled a list of additional resources which . These materials range from YouTube PlayLists/tutorials to insightful blogs and books.

### CODE REVIEW

**Comment by danvega** [comment]
I have already merged in Divitro, can you remove that from your PR?

**Comment by mikhi-mh** [comment]
I have removed it. 
Can you please check and merge @danvega now?

**Comment by mikhi-mh** [comment]
I have rebased my branch with recent changes and removed the already added Link (Divitro).
I have added one YouTube channel, some blogs, one book, and one community.

**Comment by danvega** [comment]
Sorry but one last change. Can you change the springer link to amazon and point to Pro Spring Boot 2? 

https://www.amazon.com/Pro-Spring-Boot-Authoritative-Microservices-ebook/dp/B07G2NSBCS

**Comment by mikhi-mh** [comment]
Sure, @danvega  !
I have updated it.

**Comment by danvega** [comment]
Thank you!

**Pull request merged**
